version: 2

models:
  - name: example_customers
    description: "Example customer model for testing baselinr dbt integration"
    tags:
      - critical
      - customer
      - test
    config:
      materialized: table
    columns:
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
          - unique
      - name: email
        description: "Customer email address"
        tests:
          - not_null
      - name: registration_date
        description: "Date customer registered"
      - name: status
        description: "Customer status"
      - name: lifetime_value
        description: "Customer lifetime value"

  - name: example_orders
    description: "Example orders model for testing baselinr dbt integration"
    tags:
      - critical
      - order
      - test
    config:
      materialized: table
    columns:
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer identifier (foreign key)"
        tests:
          - not_null
      - name: amount
        description: "Order amount"
        tests:
          - not_null
      - name: order_date
        description: "Date order was placed"
      - name: status
        description: "Order status"
